# Generated by Django 3.2.6 on 2021-08-06 00:55

import apps.association.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to=apps.association.models.path_and_rename, verbose_name='imagen')),
            ],
            options={
                'verbose_name': 'Bolsa de Trabajo',
                'verbose_name_plural': 'Bolsa de Trabajo',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nombre')),
                ('email', models.EmailField(max_length=255, verbose_name='email')),
                ('subject', models.CharField(max_length=256, verbose_name='asunto')),
                ('message', models.TextField(blank=True, null=True, verbose_name='mensaje')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='nombres')),
                ('last_name', models.CharField(max_length=150, verbose_name='apellidos')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='teléfono')),
                ('mobile', models.CharField(blank=True, max_length=30, null=True, verbose_name='celular')),
            ],
            options={
                'verbose_name': 'Socio',
                'verbose_name_plural': 'Socios',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='título')),
                ('short_description', models.CharField(max_length=256, verbose_name='descripción corta')),
                ('body', models.TextField(verbose_name='cuerpo')),
                ('publication_date', models.DateTimeField(auto_now_add=True, verbose_name='fecha de publicacion')),
            ],
        ),
        migrations.CreateModel(
            name='Executive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(choices=[(0, 'Presidente'), (1, 'Vicepresidente'), (2, 'Tesorero'), (3, 'Secretario'), (4, 'Miembro Vocal'), (5, 'Miembro Titular'), (6, 'Miembro Suplente')])),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='association.partner')),
            ],
            options={
                'verbose_name': 'Junta Directiva',
                'verbose_name_plural': 'Junta Directiva',
            },
        ),
    ]
