# Generated by Django 3.2.6 on 2021-08-08 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='executive',
            options={'ordering': ['position'], 'verbose_name': 'Comisión Directiva', 'verbose_name_plural': 'Comisión Directiva'},
        ),
        migrations.AlterModelOptions(
            name='joboffer',
            options={'ordering': ['-id'], 'verbose_name': 'Bolsa de Trabajo', 'verbose_name_plural': 'Bolsa de Trabajo'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'Socio', 'verbose_name_plural': 'Socios'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-publication_date'], 'verbose_name': 'Publicación', 'verbose_name_plural': 'Publicaciones'},
        ),
        migrations.AddField(
            model_name='joboffer',
            name='publication_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='fecha de publicacion'),
        ),
        migrations.AlterField(
            model_name='executive',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='association.partner', verbose_name='socio'),
        ),
        migrations.AlterField(
            model_name='executive',
            name='position',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Presidente'), (1, 'Vicepresidente'), (2, 'Tesorero'), (3, 'Secretario'), (4, 'Miembro Vocal'), (5, 'Miembro Titular'), (6, 'Miembro Suplente')], verbose_name='cargo'),
        ),
    ]
