# Generated by Django 3.2.6 on 2021-08-08 19:21

import apps.association.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0004_auto_20210808_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joboffer',
            name='description',
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='image',
            field=models.ImageField(max_length=255, null=True, upload_to=apps.association.models.path_and_rename, verbose_name='imagen'),
        ),
    ]
