# Generated by Django 3.2.6 on 2021-08-13 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0006_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.PositiveSmallIntegerField(choices=[(0, 'facebook'), (1, 'twitter'), (2, 'instagram'), (3, 'tiktok'), (4, 'whatsapp'), (5, 'youtube'), (6, 'linkedin'), (7, 'github')], verbose_name='página')),
                ('link', models.URLField()),
            ],
            options={
                'verbose_name': 'Redes sociales',
            },
        ),
    ]
