# Generated by Django 3.2.6 on 2021-08-13 07:27

import apps.association.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0007_socialnetwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='nombres')),
                ('last_name', models.CharField(max_length=150, verbose_name='apellidos')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='teléfono')),
                ('mobile', models.CharField(blank=True, max_length=30, null=True, verbose_name='celular')),
                ('diploma', models.ImageField(max_length=255, upload_to=apps.association.models.path_and_rename3)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion')),
            ],
            options={
                'verbose_name': 'Solicitudes de asociación',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='socialnetwork',
            options={'verbose_name': 'Red social', 'verbose_name_plural': 'Redes sociales'},
        ),
    ]
